"""create_loan_model.

Revision details for database migration.

Revision ID: 86c7c21a90c4
Revises: dfcb9d2ea251
Create Date: 2026-08-29 19:20:07.007944
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c7c21a90c4'
down_revision: Union[str, None] = 'dfcb9d2ea251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('loaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_book_id'), 'loans', ['book_id'], unique=False)
    op.create_index(op.f('ix_loans_created_at'), 'loans', ['created_at'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=True)
    op.create_index(op.f('ix_loans_loaned_at'), 'loans', ['loaned_at'], unique=False)
    op.create_index(op.f('ix_loans_member_id'), 'loans', ['member_id'], unique=False)
    op.create_index(op.f('ix_loans_returned_at'), 'loans', ['returned_at'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index(op.f('ix_loans_updated_at'), 'loans', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_updated_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_returned_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_member_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_loaned_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_created_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_book_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
